# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: vanminh.me
email: vanminhswe@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  My personal updates on stuff that nobody should
  care about unless I died and you are finding out why
  (a hater did it)
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.vanminh.me" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: HedghogBrr
github_username:  IntrovertHedgehog

# Build settings
theme: minima
plugins:
  - jekyll-feed

minima:
  skin: solarized-light
  social_links:
    - title: Me on GitHub
      icon: github
      url: "https://www.github.com/IntrovertHedgehog"
    - title: Me on X
      icon: x-twitter
      url: "https://x.com/HedghogBrr"
    - title: Me on Facebook
      icon: facebook
      url: "https://www.facebook.com/Fillbrick"
    - title: Me on Linkedin
      icon: linkedin
      url: "https://www.linkedin.com/in/hedgehog0409"
    - title: Me on CodeForces
      icon: code
      url: "https://codeforces.com/profile/larby2409"
  nav_pages:
    - about.md

author:
  name: Le Van Minh
  email: vanminhswe@gmail.com

exclude:
  - .tmp
  - README.md

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
  - 
    scope:
      path: ""
      type: "pages"
    values:
      show_title: true


show_drafts: true

kramdown:
  math_engine: katex

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
